### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by mauro3** [pwl/ODE.jl#10]
I think it would be good to rename some files:
- make a integrator or solver folder for `ode23s.jl`, `runge-kutta.jl`, etc.
- rename `interfaces.jl` to `user-interface.jl` as it is unclear whether this pertains to the user or solver interface
- maybe rename `types.jl` to `core.jl` or `base.jl`

**Comment by pwl** [comment]
How about `RKIntegrator<:AbstractIntegrator<:AbstractStepper`?

**Comment by pwl** [comment]
I like `base.jl` and `user-interface.jl` seems fine to me.  On the other hand, `user-interface.jl` would suggest that this is the only interface available.

**Comment by pwl** [comment]
On the other hand, `user-interface.jl` would suggest that this is the only interface available.

**Comment by mauro3** [comment]
How about high-level-interface.jl?

**Comment by pwl** [comment]
`top-interface.jl`, `ode-interface.jl`, `odeXX-interface.jl`, `simple-interface.jl`, `basic-interface.jl`, `compact-interface.jl`, (others to come...)

**Comment by mauro3** [comment]
`top-interface.jl`

**Comment by pwl** [comment]
Also we could rename `Stepper` to `Solver` and `Solver` to `???`

**Comment by mauro3** [comment]
Wait, that is a comment for #9!
