### ISSUE TITLE
Tests for generic numeric types

### ISSUE THREAD

**Issue by pwl** [pwl/ODE.jl#20]
We should add the tests for custom numeric types our solvers work with.  A list of minimal required ops should be put up in docs.

**Comment by mauro3** [comment]
Yes, this is an excellent idea.

I think #20 and #21 can be combined into one `test(solver, y_type)` or some such.

**Comment by pwl** [comment]
I would like to keep these functions in a separate module, if you are using `ODE` you don't necessarily need the tests at the same time.

**Comment by mauro3** [comment]
Ok.

**Comment by pwl** [comment]
It looks to me like `test(solver, y_type)` will never be possible because specify a type doesn't necessarily convey the complete information about the particular instances.  For instance, to construct an `Array` you need its size apart from the type itself.  Of course, if you plan on only using arrays this approach could work but it becomes hopeless if you allow arbitrary types (you don't know a priori what additional information the constructor needs).  So, all things concerned, I believe we will have to settle down with a specific test case(s) for custom types.

EDIT: Or you could have a bunch of `if`s trying to determine how to construct an instance.

**Comment by mauro3** [comment]
Yep, fair enough.

**Comment by pwl** [comment]
Closing thanks to #19.
